### PR TITLE
re-write of findAncestor

### LINKED ISSUE #2240: adaptModel.findAncestor triggers an error if no ancestor of that type exists
### Subject of the issue/enhancement/features
If you do a [findAncestor](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/adaptModel.js#L242-L259) search on a contentObject to see if it has a contentObject as its ancestor - and it doesn't - an error is thrown.

(Kineo's [pageIncompletePrompt extension](https://github.com/cgkineo/adapt-pageIncompletePrompt) does this to check to see if learner is being routed to a child page of the current page)

### Your environment
Any

### Steps to reproduce
Execute the following in the console:
```js
require('core/js/adapt').findById('co-05').findAncestor('contentObjects');
```

### Expected behaviour
no error should occur, the function should simply return `undefined` to indicate that no results were found

### Actual behaviour
The error 'TypeError: returnedAncestor is undefined' is thrown.

### PR DESCRIPTION
**Pull request by moloko**
to fix #2240 

also remove call to `setOptional` from `setupModel` - it wasn't actually doing anything and we wouldn't want to be forcing children to be optional anyway

general tidy-up to:
* change `_.bind` to `Function.bind`
* improve comments
* use best version of `model.set` as appropriate
* remove unused variables

### CODE REVIEW

File: src/core/js/models/adaptModel.js [hunk 1]
```diff
@@ -239,29 +238,28 @@ define([
...
+         * @param {string} [ancestorType] Valid values are 'course', contentObjects', 'articles' or 'blocks'.
+         * If left blank, the immediate ancestor (if there is one) is returned
+         * @return {object} Reference to the model of the first ancestor of the specified type that's found - or `undefined` if none found
+         */
+        findAncestor: function (ancestorType) {
             var parent = this.getParent();
+            if (!parent) return;
 
-            if (this._parent === ancestors) {
+            if (!ancestorType || ancestorType === "" || this._parent === ancestorType) {
```
Comment (tomgreenfield) [inline src/core/js/models/adaptModel.js]: Redundant logic – empty strings are already caught by `!ancestorType`.
