### PR TITLE
fixes for bad PLP scroll

### LINKED ISSUE #3074: PLP: odd scrolling behaviour on clicking item
Using FW v5.11.0/master, use the PLP to navigate to a component that's outside of the viewport.

Instead of scrolling smoothly to the component, adapt kind-of 'jumps' to a component near it then scrolls the last part.

Suspect issue has been around for a while but only became obvious since we fixed #3022

### PR DESCRIPTION
**Pull request by moloko**
fixes #3074

### CODE REVIEW

File: src/core/js/views/drawerView.js [hunk 1]
```diff
@@ -211,7 +211,7 @@ class DrawerView extends Backbone.View {
     const direction = {};
     // only trigger popup:closed if drawer is visible
     if (this._isVisible) {
-      Adapt.a11y.popupClosed($toElement);
+      Adapt.a11y.focusFirst($($toElement), { preventScroll: true });
```
Comment (oliverfoster) [inline src/core/js/views/drawerView.js:214]: Revert this one.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]

**Review by chris-steele — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

**Review by danielghost — APPROVED** [review]
