### PR TITLE
issue/2796 Minor additional fixes

### LINKED ISSUE #2796: Question component - Marking should only be displayed on final question attempt
### Subject of the enhancement
The Question component could benefit from a 'Display Final Marking Only' type setting

### Your environment
* FW5

### Steps to reproduce
Create a course with Matching Question components with multiple question stems; each question having only 2 possible answers and the user has 2 attempts.

### Expected behaviour
The component could be set to only display marking on the final attempt

### Actual behaviour
After the first attempt, the marking is displayed, making it quite obvious to the user what the correct answers are for each Matching Question

### PR DESCRIPTION
**Pull request by oliverfoster**
#2796 
### Fixed
* buttons template so that correctness aria label doesn't appear immediately
* Question view `can-show-marking` class should appear when property is set
* `QuesitonModel.canShowMarking` return true if property set and component interaction is complete

### CODE REVIEW

**Comment by oliverfoster** [comment]
@moloko I think that might be about it?

**Comment by moloko** [comment]
worth adding a comment to the `canShowMarking` getter to clarify that its purpose is determine when marking _should_ be shown rather than just returning the value of `_canShowMarking`...?

File: src/core/js/models/questionModel.js [hunk 1]
```diff
@@ -321,7 +321,7 @@ define([
     getResponseType() {}
 
     /** @type {boolean} */
-    get canShowMarking() {
+    get shouldShowMarking() {
```
Comment (moloko) [inline src/core/js/models/questionModel.js:324]: much better!

Comment (oliverfoster) [reply src/core/js/models/questionModel.js:324]: I don't see why not, seeing as it's brand new.

File: src/core/js/models/questionModel.js [hunk 2]
```diff
@@ -321,16 +321,12 @@ define([
...
       if (!this.get('_canShowMarking')) {
         return false;
       }
 
-      const attemptsLeft = this.get('_attemptsLeft');
-      const hasMultipleAttempts = this.get('_attempts') > 1;
-      const isFinalAttempt = !hasMultipleAttempts || (attemptsLeft === 0);
-
-      return isFinalAttempt;
+      return this.get('_isInteractionComplete');
```
Comment (oliverfoster) [inline src/core/js/models/questionModel.js:329]: This works because all the attempts checking stuff has to happen before _isInteractionComplete is set so it become implied here.

File: src/core/js/views/questionView.js [hunk 3]
```diff
@@ -308,7 +308,7 @@ define([
     refresh() {
       this.model.set('_buttonState', this.model.getButtonState());
 
-      if (this.model.canShowMarking && this.model.get('_isInteractionComplete') && this.model.get('_isSubmitted')) {
+      if (this.model.shouldShowMarking && this.model.get('_isInteractionComplete') && this.model.get('_isSubmitted')) {
```
Comment (moloko) [inline src/core/js/views/questionView.js:311]: seeing as `shouldShowMarking` now checks `_isInteractionComplete`...
```suggestion
      if (this.model.shouldShowMarking && this.model.get('_isSubmitted')) {
```

File: src/core/templates/buttons.hbs [hunk 4]
```diff
@@ -1,6 +1,6 @@
 <div class="btn__response-container">
 
-  <div class="btn__marking js-btn-marking u-display-none" aria-label="{{#if _isCorrect}}{{@root/_globals._accessibility._ariaLabels.answeredCorrectly}}{{else}}{{@root/_globals._accessibility._ariaLabels.answeredIncorrectly}}{{/if}}">
+  <div class="btn__marking js-btn-marking u-display-none" aria-label="{{#all _isInteractionComplete _canShowMarking}}{{#if _isCorrect}}{{@root/_globals._accessibility._ariaLabels.answeredCorrectly}}{{else}}{{@root/_globals._accessibility._ariaLabels.answeredIncorrectly}}{{/if}}{{/all}}">
```
Comment (moloko) [inline src/core/templates/buttons.hbs:3]: could the getter be used here instead?
```suggestion
  <div class="btn__marking js-btn-marking u-display-none" aria-label="{{#if canShowMarking}}{{#if _isCorrect}}{{@root/_globals._accessibility._ariaLabels.answeredCorrectly}}{{else}}{{@root/_globals._accessibility._ariaLabels.answeredIncorrectly}}{{/if}}{{/all}}">
```

Comment (oliverfoster) [reply src/core/templates/buttons.hbs:3]: No. The data in the handlebars content is not the model it's just a json object from model.attributes / model.toJSON() so there is no reference to the canShowMarking property.
