### PR TITLE
Fix: Warn if incompatible plugins are being compiled (fixes #3321)

### LINKED ISSUE #3321: warn if incompatible plugins are being compiled
plugin package.json:framework vs framework package.json and warn if semver doesn't match

### PR DESCRIPTION
**Pull request by swashbuck**
Fixes #3321

### New
* Throws an error if required framework version in a plugin is not satisfied by the current framework version

### Testing
1. In a plugin's _bower.json_, set `framework` to a high value like `>=7.0.0`

### CODE REVIEW

**Comment by oliverfoster** [comment]
Awesome

**Review by oliverfoster — APPROVED** [review]

**Comment by oliverfoster** [comment]
Error or warn? Thinking AAT...

**Comment by swashbuck** [comment]
> Error or warn? Thinking AAT...

@oliverfoster Is the concern that throwing an error would prevent a course from building, but a warning would not interfere since it just outputs a message?

**Comment by oliverfoster** [comment]
Only in theory. I don't actually know what would happen or what's worse or if the user would get the appropriate message.

**Comment by swashbuck** [comment]
> Only in theory. I don't actually know what would happen or what's worse or if the user would get the appropriate message.

Doesn't `adapt-cli` prevent incompatible plugins from being uploaded? So, in theory, you would never get to the point where you're trying to build a course in the AAT with an incompatible plugin.

**Comment by oliverfoster** [comment]
You can use the `adapt-cli` or the AAT plugin upload to install a plugin in a course. Or you can download a plugin and unzip it in the right place.

**Comment by swashbuck** [comment]
> You can use the `adapt-cli` or the AAT plugin upload to install a plugin in a course. Or you can download a plugin and unzip it in the right place.

Ok, probably safer to just use a warn. Same as the "Plugin folder name ${pathDerivedName} does not match package name" message.

**Review by joe-allen-89 — APPROVED** [review]
👍

File: grunt/helpers/plugins/Plugin.js [hunk 1]
```diff
@@ -96,6 +100,18 @@ class Plugin {
...
   }
 
+  /** @returns {string} */
+  get requiredFramework() {
+    return this.packageJSONFile.firstFileItem.item.framework;
+  }
+
+  /** @returns {boolean} */
+  get isFrameworkCompatible() {
+    if (!this.framework || !this.framework.version) return;
```
Comment (cahirodoherty-learningpool) [inline grunt/helpers/plugins/Plugin.js:110]: Can we return `true` here and then apply a boolean check on line 66? (i.e. `!this.isFrameworkCompatible`)

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀
