### PR TITLE
Fixes #1917, adds a 'drawer:remove' event to handle drawer tidy-up

### LINKED ISSUE #1917: Drawer icon is removed when changing language
### Subject of the issue
When creating a multi-language course the Drawer icon is removed when you change language mid-way through a course.

### Your environment
* Framework version 2.2.3
* IE11
* Windows 7

### Steps to reproduce
- Download and install the latest version of the framework (2.2.3)
- Duplicate the course/en folder and rename to 'de' for German.
- Enable language picker in config.json
- Build and preview course.
- Choose the English version on the language picker.
- Open language picker on the nav bar.
- Change language to German.

### Expected behaviour
Drawer icon should remain in the nav bar.

### Actual behaviour
Drawer icon is removed from the nav bar.

### PR DESCRIPTION
**Pull request by brian-learningpool**
The Drawer wasn't tidying up after itself and left multiple views dangling each time a language was changed while a course was in progress.

This remedies it by triggering a 'drawer:remove' event to remove the drawer completely when 'app:languageChanged' is triggered.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Associated PR on the way for Resources.

File: src/core/js/drawer.js [hunk 1]
```diff
@@ -18,17 +18,12 @@ define([
...
 
-    var init = function() {
-        var drawerView = new DrawerView({collection: DrawerCollection});
-
-        Adapt.on('app:languageChanged', function() {
-            drawerView.remove();
-            drawerView = new DrawerView({collection: DrawerCollection});
-        });
-    };
+    Adapt.on('adapt:start', function() {
```
Comment (tomgreenfield) [inline src/core/js/drawer.js]: Would you mind switching to object syntax instead of the two `.on()` calls?
```js
Adapt.on({
    'adapt:start': function() { new DrawerView({ collection: DrawerCollection }); },
    'app:languageChanged': function() { Adapt.trigger('drawer:remove'); }
});
```

File: src/core/js/drawer.js [hunk 2]
```diff
@@ -18,17 +18,13 @@ define([
...
-            drawerView.remove();
-            drawerView = new DrawerView({collection: DrawerCollection});
-        });
-    };
-
-    Adapt.once('adapt:start', function() {
-        init();
+    Adapt.on({
+        'adapt:start': function() {
+             new DrawerView({ collection: DrawerCollection });
```
Comment (tomgreenfield) [inline src/core/js/drawer.js]: Extra space here which I now can't unsee!

Comment (oliverfoster) [reply src/core/js/drawer.js]: xD

**Comment by brian-learningpool** [comment]
Thanks for the reviews, guys.  I'll get this into legacy tomorrow.
