### PR TITLE
Resolves #2480, adds a guard on '_items' property

### LINKED ISSUE #2480: Defensive checks required around setUpItems()
This is a bit of an edge case, but if an accordion component is added which does not contain any _items, the `setUpItems` function here (https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/itemsComponentModel.js#L24) fails and never runs for any subsequent components.  As such the `toJSON()` call in the same code fails because `_children` is null and prevents the course from rendering.

### PR DESCRIPTION
**Pull request by brian-learningpool**
If '_items' was not set this would throw an error which would prevent the content from loading.

### CODE REVIEW

File: src/core/js/models/itemsComponentModel.js [hunk 1]
```diff
@@ -21,7 +21,7 @@ define([
         },
 
         setUpItems: function() {
-            var items = this.get('_items');
+            var items = this.get('_items') || [];
```
Comment (moloko) [inline src/core/js/models/itemsComponentModel.js]:
```suggestion
            var items = this.get('_items') || []; // see https://github.com/adaptlearning/adapt_framework/issues/2480
```
