### PR TITLE
Resolves #2439, adds a timeout to Adapt.wait

### LINKED ISSUE #2439: Adapt.wait should implement a timeout in order to prevent blocking of rendering
### Subject of the enhancement
The `Adapt.wait` API has `begin()` and `end()` calls but in cases where calls to `begin()` do not have a corresponding call to `end()` (for whatever reason) it can result in a course failing to load and difficult to diagnose errors.

### Your environment
Adapt Framework v3.5.3

### Steps to reproduce
Inside a plugin call `Adapt.wait.begin()` and do not call `Adapt.wait.end()`.

### Expected behaviour
After a given timeout, the queue should be flushed together with a debug message logged to the console to indicate as such.

### Actual behaviour
The Adapt content appears to get stuck in an intermediate state between loading and rendering.

### PR DESCRIPTION
**Pull request by brian-learningpool**
To prevent an unhandled expection or a call to begin() not having a corresponding end() from blocking rendering of the Adapt content, a 7-second timeout is now added on every begin.  If the time has elapsed since the last begin() the outstanding calls to Adapt.wait.end() will be triggered.

Also added a _.once() call to the for() callback and replaced double quote marks in strings with single quotes.

### CODE REVIEW

File: src/core/js/wait.js [hunk 1]
```diff
@@ -18,6 +20,35 @@ define(function() {
...
 
+        /**
+         * Starts or re-starts a timer to ensure that pending calls to end()
+         * are actually executed after a timeout period.
+         */
+        startTimer: function() {
+            this.stopTimer();
+
+            this._timeoutHandlerId = setInterval(function() {
+              // Flush Adapt.wait due to timeout
```
Comment (oliverfoster) [inline src/core/js/wait.js]: Mixed indentation

File: src/core/js/wait.js [hunk 2]
```diff
@@ -98,7 +129,7 @@ define(function() {
 
             this.begin();
             _.defer(function() {
-                callback(this.end);
+                _.once(callback(this.end));
```
Comment (oliverfoster) [inline src/core/js/wait.js]:
```js
callback(_.once(this.end));
```

Comment (brian-learningpool) [reply src/core/js/wait.js]: Whoops!  Good catch. 👍

**Comment by brian-learningpool** [comment]
@oliverfoster, it wasn't intended.  I had multiple framework version checkouts and it looks like I pushed one in an intermediate state.

I intended to trigger `startTimer()` whenever `begin()` is called.

File: src/core/js/wait.js [hunk 3]
```diff
@@ -36,6 +67,8 @@ define(function() {
                 this._callbackHandle = null;
             }
 
+            this.startTimer();
```
Comment (oliverfoster) [inline src/core/js/wait.js]: Ahh yea, s'all good.
